# Generated by Django 5.0.7 on 2025-06-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Cutting', 'Cutting Started'), ('Stitching', 'Stitching'), ('Trial', 'Trial Ready'), ('Delivery', 'Out for Delivery'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Received', max_length=20),
        ),
    ]
