# Generated by Django 5.0.7 on 2025-06-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='design_image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/'),
        ),
    ]
