# Generated by Django 5.0.7 on 2025-06-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_design_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='design_image',
            field=models.ImageField(blank=True, help_text='Customer uploaded design sketch or reference image', null=True, upload_to='designs/'),
        ),
    ]
